# Generated by Django 4.2.2 on 2024-07-02 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0003_worker_creator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="creator",
        ),
    ]
