# Generated by Django 4.2.1 on 2023-05-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0006_tag_tasks_remove_tag_name_tag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tasks",
        ),
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                default=None, related_name="tags", to="task_manager.tag"
            ),
        ),
    ]
