# Generated by Django 4.2.1 on 2023-05-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0007_remove_tag_tasks_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                default=None, related_name="tasks", to="task_manager.tag"
            ),
        ),
    ]
