# Generated by Django 4.2.1 on 2023-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0009_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                null=True,
                related_name="tasks",
                to="task_manager.tag",
            ),
        ),
    ]
