# Generated by Django 4.2.1 on 2023-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0010_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, default=None, related_name="tasks", to="task_manager.tag"
            ),
        ),
    ]
