# Generated by Django 4.2.1 on 2023-05-30 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0011_alter_task_tags"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="worker",
            managers=[],
        ),
    ]
