# Generated by Django 4.2.1 on 2023-06-04 11:29

from django.db import migrations
from django.db.migrations import RunPython


def reverse_func(apps, schema_editor):
    pass


def func(apps, schema_editor):
    from django.core.management import call_command
    import sys

    if "test" not in sys.argv:
        call_command("loaddata", "task_manager_db_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0013_alter_worker_managers"),
    ]

    operations = [
        RunPython(func, reverse_func),
    ]
