# Generated by Django 4.2.2 on 2023-06-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0014_auto_20230604_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
