# Generated by Django 4.2.2 on 2023-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0015_task_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="slug",
            field=models.SlugField(allow_unicode=True, blank=True),
        ),
    ]
